### ISSUE TITLE
Updated/generalized version

### ISSUE THREAD

**Issue by davenquinn** [tomgp/d3-ternary#1]
Hi Tom,

I made a generalized ternary diagram library (http://github.com/davenquinn/d3-ternary) using this project as a starting point. It accomplishes a superset of what you've got here (including axis labeling and resizability), so I just wanted to make you aware. It could provide a good base for focusing further efforts.

Cheers,
Daven

**Comment by tomgp** [comment]
Thanks Dave. Only just noticed your comment! I'm going to be revisiting this project soon, making so this'll be very helpful!
